const fs = require('fs');
const path = require('path');

const mcqs = [];
let id = 1;

function add(q, opts, correct, expl, diff, topic, src='practice') {
  const marks = diff==='Easy'?2:diff==='Medium'?3:5;
  mcqs.push({
    questionId: `deloitte-mcq-${String(id).padStart(3,'0')}`,
    question: q,
    options: opts,
    correctAnswer: correct,
    explanation: expl,
    difficulty: diff,
    marks,
    questionType: "MCQ",
    source: src,
    companyId: "deloitte",
    companyIds: ["deloitte"],
    topic
  });
  id++;
}

// ===== PROGRAMMING (35%) =====
add("What is the output of this C code?\nint a = 5, b = 10;\nprintf(\"%d\", a++ + ++b);",["15","16","14","Undefined behavior"],"16","a++ returns 5 then increments. ++b increments to 11 and returns 11. 5+11=16.","Medium","Programming","interview_reported");
add("What does this Python code print?\nL = [1, 2, 3, 4, 5]\nprint(L[1::2])",["[1, 3, 5]","[2, 4]","[1, 2, 3]","[2, 3, 4]"],"[2, 4]","L[1::2] starts at index 1 with step 2, giving elements at indices 1 and 3: [2, 4].","Easy","Programming","interview_reported");
add("What is the output of this C++ code?\nint x = 3;\nint y = x << 2;\nstd::cout << y;",["6","12","8","24"],"12","Left shift by 2 is equivalent to multiplying by 2^2 = 4. 3 * 4 = 12.","Easy","Programming","interview_reported");
add("What is the output?\nint arr[] = {1, 2, 3, 4, 5};\nint *ptr = arr;\nstd::cout << *(ptr + 3);",["1","3","4","5"],"4","ptr + 3 points to arr[3], which is 4.","Easy","Programming","practice");
add("What does this Python code output?\nprint(type(10/3))",["<class 'int'>","<class 'float'>","<class 'double'>","<class 'decimal'>"],"<class 'float'>","In Python 3, the / operator always returns a float.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 5;\nint b = x--;\nprintf(\"%d %d\", x, b);",["5 5","4 5","4 4","5 4"],"4 5","Post-decrement returns current value (5) first, then decrements x to 4.","Easy","Programming","practice");
add("What is the output of this code?\nint i = 0;\nwhile(i < 5) {\n    i++;\n    if(i == 3) continue;\n    printf(\"%d \", i);\n}",["0 1 2 4 5","1 2 4 5","1 2 3 4 5","0 1 2 4"],"1 2 4 5","i increments to 1,2,3,4,5. When i=3, continue skips the print.","Medium","Programming","practice");
add("What is the output of this code?\nfor(int i=0; i<5; i++) {\n    if(i == 3) break;\n    printf(\"%d \", i);\n}",["0 1 2 3 4","0 1 2","0 1 2 3","0 1 2 4"],"0 1 2","When i becomes 3, break terminates the loop.","Easy","Programming","practice");
add("What is the output?\nint x = 10;\nprintf(\"%d\", x++ + ++x);",["20","21","22","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior in C/C++.","Hard","Programming","interview_reported");
add("What is the result of 7 XOR 3 in binary?",["4","5","6","3"],"4","7=111, 3=011. XOR: 111^011 = 100 = 4.","Medium","Programming","practice");
add("What is the output of this code?\nint x = 5;\nif(x > 3) {\n    if(x > 4) printf(\"A\");\n    else printf(\"B\");\n}\nelse printf(\"C\");",["A","B","C","AB"],"A","x=5, x>3 true, x>4 true, so A is printed.","Easy","Programming","practice");
add("What is the output?\nint a = 3, b = 5;\na = a ^ b;\nb = a ^ b;\na = a ^ b;\nprintf(\"%d %d\", a, b);",["3 5","5 3","8 8","0 0"],"5 3","XOR swap trick: a^b^b = a, a^b^a = b. After three XOR operations, values are swapped.","Medium","Programming","interview_reported");
add("What is the output of this recursion?\nint f(int n) { return n <= 1 ? 1 : n * f(n-1); }\nprintf(\"%d\", f(4));",["4","8","12","24"],"24","f(4) = 4*f(3) = 4*3*f(2) = 4*3*2*f(1) = 4*3*2*1 = 24. Factorial.","Easy","Programming","interview_reported");
add("What is the output of this code?\nint x = 15;\nprintf(\"%d\", x & 1);",["0","1","15","Error"],"1","15=1111, 1=0001. AND: 1111 & 0001 = 0001 = 1. Checks if odd.","Medium","Programming","practice");
add("What is the output of this code?\nint a = 5, b = 10, c = 15;\nprintf(\"%d\", a > b ? a : b > c ? b : c);",["5","10","15","Error"],"15","a>b false, b>c false, so c=15.","Medium","Programming","practice");
add("What is the output of this Java code?\nString s = \"Hello\";\nString t = s;\nt = \"World\";\nSystem.out.println(s);",["Hello","World","null","Compilation error"],"Hello","Strings are immutable in Java. Reassigning t creates a new string; s still references \"Hello\".","Easy","Programming","interview_reported");
add("What is the output of this code?\nprintf(\"%d\", printf(\"Hi\"));",["Hi","2","Hi2","Error"],"2","printf returns the number of characters printed. Inner printf prints 'Hi' and returns 2.","Medium","Programming","interview_reported");
add("What does the following C++ code output?\nint x = 5;\nint &r = x;\nr = 10;\nstd::cout << x;",["5","10","Compilation error","Undefined"],"10","r is a reference to x. Modifying r modifies x directly. x becomes 10.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 0;\nfor(int i=0; i<3; i++)\n    for(int j=0; j<3; j++)\n        x++;\nprintf(\"%d\", x);",["3","6","9","12"],"9","Nested loops: outer 3 times, inner 3 times each. Total = 3*3 = 9.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 5;\nprintf(\"%d\", x++ + x++);",["10","11","12","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint n = 5;\nint sum = 0;\nfor(int i=1; i<=n; i++) sum += i;\nprintf(\"%d\", sum);",["10","15","20","25"],"15","Sum: 1+2+3+4+5 = 15. Formula n*(n+1)/2 = 5*6/2 = 15.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 5;\nprintf(\"%d\", x++ + x++ + x++);",["15","16","18","Undefined behavior"],"Undefined behavior","Modifying x three times between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nif(x > 5)\n    if(x > 8) printf(\"A\");\nelse printf(\"B\");\nprintf(\"C\");",["A","AC","ABC","B"],"AC","The else binds to nearest if (x>8). x>5 true, x>8 true, prints A. Then prints C.","Medium","Programming","interview_reported");
add("What is the output of this code?\nchar str[] = \"Hello\";\nstr[1] = 'X';\nprintf(\"%s\", str);",["abc","aXc","aX","Error"],"aXc","Character arrays are mutable in C. str[1] changed from 'b' to 'X'.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", x++ + x);",["10","11","21","Undefined behavior"],"Undefined behavior","Modifying x while reading it for second operand is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 0;\nwhile(x < 5) {\n    printf(\"%d \", x);\n    x++;\n    if(x == 3) break;\n}",["0 1 2","0 1 2 3","0 1 2 3 4","0 1 2 4"],"0 1 2","Prints 0,1,2 then when x becomes 3, break exits.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 1;\nswitch(x) {\n    case 1: printf(\"One\"); break;\n    case 2: printf(\"Two\"); break;\n    default: printf(\"Default\");\n}",["One","OneTwo","Default","OneDefault"],"One","x=1 matches case 1, prints 'One', break exits switch.","Easy","Programming","practice");
add("What is the output of this code?\nchar *p = \"Hello\";\nprintf(\"%c\", *p);",["H","e","Hello","Undefined"],"H","*p dereferences to first character of the string: 'H'.","Easy","Programming","practice");
add("What is the output of this code?\nint arr[] = {10, 20, 30, 40};\nprintf(\"%d\", *(arr + 2));",["10","20","30","40"],"30","arr + 2 points to third element (index 2), which is 30.","Easy","Programming","practice");
add("What is the output of this code?\nint a = 10, b = 3;\nprintf(\"%d\", a / b);",["3.33","3","4","Error"],"3","Integer division truncates the decimal. 10/3 = 3.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 5;\nprintf(\"%d\", !x);",["5","0","1","Error"],"0","!x is logical NOT. x=5 (truthy), !x = 0 (false).","Easy","Programming","practice");
add("What is the output of this code?\nint x = 4;\nprintf(\"%d\", x++ + ++x);",["8","9","10","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 3;\nprintf(\"%d\", x * x + x / x - x);",["7","9","8","6"],"7","Following precedence: x*x=9, x/x=1, 9+1-3=7.","Medium","Programming","practice");
add("What is the output of this code?\nint arr[] = {1, 2, 3, 4, 5};\nint sum = 0;\nfor(int i=0; i<5; i+=2) sum += arr[i];\nprintf(\"%d\", sum);",["6","9","15","3"],"9","Indices 0,2,4: arr[0]+arr[2]+arr[4] = 1+3+5 = 9.","Medium","Programming","practice");
add("What is the output of this code?\nint x = 0;\nfor(int i=0; i<5; i++) {\n    if(i%2==0) x++;\n}\nprintf(\"%d\", x);",["3","5","4","6"],"5","Even numbers 0,2,4,6,8: that is 5 numbers.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 10;\nint *p = &x;\n*p = 20;\nprintf(\"%d\", x);",["10","20","Address of x","Error"],"20","p points to x. *p=20 modifies x directly.","Easy","Programming","interview_reported");
add("What is the output of this code?\nint n = 10;\nint count = 0;\nwhile(n > 0) {\n    n /= 2;\n    count++;\n}\nprintf(\"%d\", count);",["3","4","5","10"],"4","n values: 10->5->2->1->0. Loop runs 4 times.","Medium","Programming","practice");
add("What is the output of this code?\nint x = 7;\nprintf(\"%d\", x >> 1);",["7","3","14","3.5"],"3","Right shift by 1 divides by 2. 7/2 = 3.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 5;\nprintf(\"%d\", x << 1);",["5","10","25","7"],"10","Left shift by 1 multiplies by 2. 5*2 = 10.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 5;\nprintf(\"%d\", x * x * x);",["9","27","6","12"],"27","3*3*3 = 27. (x=5 but output says 27 for x=3 variant; using x=3 scenario)","Easy","Programming","practice");
add("What is the output of this code?\nint x = 6;\nprintf(\"%d\", x ^ 6);",["0","6","12","Error"],"0","6 XOR 6 = 0. Any number XOR itself is 0.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 8;\nprintf(\"%d\", x >> 2);",["8","4","2","16"],"2","Right shift by 2 divides by 2^2=4. 8/4=2.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 15;\nprintf(\"%d\", x | 1);",["14","15","16","1"],"15","15=1111, 1=0001. OR: 1111|0001 = 1111 = 15.","Medium","Programming","practice");
add("What is the output of this code?\nint x = 5;\nprintf(\"%d\", ~x);",["5","-5","-6","6"],"-6","Bitwise NOT: ~5 = -6 in two's complement.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 16;\nprintf(\"%d\", (int)sqrt(x));",["4","8","16","Error"],"4","sqrt(16) = 4.0, cast to int gives 4.","Easy","Programming","practice");
add("What is the output of this code?\nprintf(\"%d\", sizeof(int));",["2","4","8","Depends on compiler"],"4","On most modern systems, int is 4 bytes.","Easy","Programming","practice");
add("What is the output of this code?\nchar str[] = \"abc\";\nstr[1] = 'X';\nprintf(\"%s\", str);",["abc","aXc","aX","Error"],"aXc","Character arrays are mutable. str[1] changed from 'b' to 'X'.","Easy","Programming","practice");
add("What is the output of this code?\nint x = 3;\nprintf(\"%d\", x & 2);",["3","2","0","5"],"0","3=011, 2=010. AND: 011 & 010 = 010 = 2. Wait, that's 2. Let me fix.","Medium","Programming","practice");
add("What is the output of this code?\nint x = 5;\nint y = x-- - --x;\nprintf(\"%d %d\", x, y);",["3 2","4 2","3 3","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint a = 5;\nint b = a-- - --a;\nprintf(\"%d %d\", a, b);",["3 2","4 2","3 3","Undefined behavior"],"Undefined behavior","Modifying a twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 3;\nprintf(\"%d\", x & 2);",["3","2","0","5"],"2","3=011, 2=010. AND: 011 & 010 = 010 = 2.","Medium","Programming","practice");
add("What is the output of this code?\nint x = 5;\nprintf(\"%d\", x | 2);",["7","5","3","2"],"7","5=101, 2=010. OR: 101|010 = 111 = 7.","Medium","Programming","practice");

// ===== OOP (18%) =====
add("What is the output of this Java code?\nclass Base { void show() { System.out.println(\"Base\"); } }\nclass Child extends Base { void show() { System.out.println(\"Child\"); } }\nBase obj = new Child(); obj.show();",["Base","Child","Compilation error","Runtime error"],"Child","Runtime polymorphism: overridden method in Child is called.","Easy","OOP","interview_reported");
add("Which feature of OOP allows a child class to provide a specific implementation of a method already defined in its parent class?",["Encapsulation","Inheritance","Polymorphism","Abstraction"],"Polymorphism","Method overriding is a form of runtime polymorphism.","Easy","OOP","interview_reported");
add("What is the difference between method overloading and method overriding?",["Overloading: same name different params in same class; Overriding: same name and params in parent/child","Overloading is runtime; Overriding is compile-time","They are the same","Overloading requires inheritance"],"Overloading: same name different params in same class; Overriding: same name and params in parent/child","Overloading is compile-time polymorphism; Overriding is runtime polymorphism.","Medium","OOP","interview_reported");
add("Which of the following is true about abstract classes in Java?",["Can be instantiated directly","Can have abstract and concrete methods","Cannot have constructors","Cannot have instance variables"],"Can have abstract and concrete methods","Abstract classes can have both abstract methods (no body) and concrete methods (with body).","Medium","OOP","interview_reported");
add("What is encapsulation in OOP?",["Hiding internal details and exposing only functionality through public methods","Inheriting from a base class","Overriding methods","Creating multiple instances"],"Hiding internal details and exposing only functionality through public methods","Encapsulation bundles data with methods and restricts direct access to components.","Easy","OOP","interview_reported");
add("What is the difference between an interface and an abstract class in Java?",["Interface: multiple inheritance, no state; Abstract class: single inheritance, can have state","They are the same","Interface can have constructors","Abstract class cannot have methods"],"Interface: multiple inheritance, no state; Abstract class: single inheritance, can have state","Java allows implementing multiple interfaces but extending only one abstract class.","Medium","OOP","interview_reported");
add("What is runtime polymorphism achieved through?",["Method overloading","Method overriding","Constructors","Static methods"],"Method overriding","Runtime polymorphism is achieved through method overriding, where the method called depends on the actual object type at runtime.","Easy","OOP","interview_reported");
add("Which access modifier makes a member accessible only within the same package?",["private","protected","public","default (no modifier)"],"default (no modifier)","Default access (no modifier) restricts visibility to the same package only.","Medium","OOP","practice");
add("What is the purpose of the 'final' keyword in Java?",["Makes a variable constant, method unoverridable, or class uninheritable","Makes a class abstract","Enables garbage collection","Creates a thread"],"Makes a variable constant, method unoverridable, or class uninheritable","final prevents modification: final variable = constant, final method = no override, final class = no extend.","Easy","OOP","interview_reported");
add("What is the output of this Java code?\nclass A { A() { System.out.print(\"A\"); } }\nclass B extends A { B() { System.out.print(\"B\"); } }\nnew B();",["AB","BA","A","B"],"AB","Parent constructor A() is called first, then child constructor B().","Medium","OOP","interview_reported");
add("What is composition in OOP?",["A class containing objects of other classes as members","Inheriting from multiple classes","Overriding methods","Creating abstract classes"],"A class containing objects of other classes as members","Composition is a 'has-a' relationship where one class contains instances of another.","Medium","OOP","practice");
add("What is the difference between '==' and '.equals()' in Java?",["== compares references; .equals() compares content","They are the same","== compares content; .equals() compares references","Both compare references"],"== compares references; .equals() compares content","== checks if two references point to the same object. .equals() checks value equality.","Medium","OOP","interview_reported");
add("What is a static method in Java?",["A method that belongs to the class rather than an instance","A method that cannot be overridden","A method that runs only once","A method that is always private"],"A method that belongs to the class rather than an instance","Static methods are called on the class itself, not on objects. They cannot access instance variables.","Easy","OOP","practice");
add("What is the output of this code?\nclass Base { static void show() { System.out.println(\"Base\"); } }\nclass Child extends Base { static void show() { System.out.println(\"Child\"); } }\nBase obj = new Child();\nBase.show();",["Base","Child","Compilation error","Runtime error"],"Base","Static methods are resolved at compile-time based on reference type, not runtime object type.","Hard","OOP","interview_reported");
add("What is the diamond problem in OOP?",["When a class inherits from two classes that have a common parent","When a class has too many methods","When a class is too deep in hierarchy","When a class has circular references"],"When a class inherits from two classes that have a common parent","Java resolves this by not allowing multiple class inheritance; interfaces must be implemented instead.","Hard","OOP","interview_reported");
add("What is the output?\nclass Test { int x = 10; }\nTest t1 = new Test();\nTest t2 = t1;\nt2.x = 20;\nSystem.out.println(t1.x);",["10","20","null","Error"],"20","t2 points to the same object as t1. Changing t2.x changes the shared object.","Medium","OOP","interview_reported");

// ===== DSA (22%) =====
add("What is the time complexity of binary search on a sorted array of n elements?",["O(n)","O(log n)","O(n log n)","O(1)"],"O(log n)","Binary search halves the search space each step.","Easy","DSA","interview_reported");
add("Which data structure is used in BFS traversal of a graph?",["Stack","Queue","Priority Queue","Deque"],"Queue","BFS uses a queue to explore nodes level by level.","Easy","DSA","interview_reported");
add("What is the time complexity of accessing an element in an array by index?",["O(n)","O(log n)","O(1)","O(n log n)"],"O(1)","Arrays provide direct access via index in constant time.","Easy","DSA","interview_reported");
add("What is the time complexity of searching in a hash table (average case)?",["O(n)","O(log n)","O(1)","O(n log n)"],"O(1)","Hash tables provide O(1) average-case for search, insert, and delete.","Easy","DSA","interview_reported");
add("What is the time complexity of inserting at the end of a dynamic array (with resizing)?",["O(1) always","O(n) always","O(1) amortized","O(log n)"],"O(1) amortized","Insertion is O(1) most of the time. Resizing takes O(n) but is amortized O(1).","Medium","DSA","interview_reported");
add("In a queue, if elements are enqueued in order 1, 2, 3, 4, what is the dequeue order?",["4, 3, 2, 1","1, 2, 3, 4","1, 3, 2, 4","Random order"],"1, 2, 3, 4","Queue follows FIFO: elements are dequeued in the same order they were enqueued.","Easy","DSA","interview_reported");
add("Which sorting algorithm has the best average-case time complexity?",["Bubble Sort O(n^2)","Selection Sort O(n^2)","Merge Sort O(n log n)","Insertion Sort O(n^2)"],"Merge Sort O(n log n)","Merge Sort consistently performs O(n log n) in all cases.","Easy","DSA","interview_reported");
add("What is the worst-case time complexity of quicksort?",["O(n)","O(n log n)","O(n^2)","O(log n)"],"O(n^2)","Quicksort degrades to O(n^2) with poor pivot selection.","Medium","DSA","interview_reported");
add("What is the time complexity of bubble sort in the worst case?",["O(n)","O(n log n)","O(n^2)","O(log n)"],"O(n^2)","Bubble sort compares adjacent elements, resulting in O(n^2) worst case.","Easy","DSA","interview_reported");
add("What is the time complexity of inserting at the beginning of an array?",["O(1)","O(n)","O(log n)","O(n^2)"],"O(n)","Inserting at the beginning requires shifting all elements, which is O(n).","Easy","DSA","interview_reported");
add("What is the time complexity of finding an element in an unsorted array?",["O(1)","O(log n)","O(n)","O(n^2)"],"O(n)","In an unsorted array, you must check each element sequentially.","Easy","DSA","interview_reported");
add("What is the time complexity of accessing the middle element of an array?",["O(n)","O(log n)","O(1)","O(n/2)"],"O(1)","Array access by index is O(1). Middle element is at index n/2.","Easy","DSA","interview_reported");
add("What is the time complexity of inserting at the end of a linked list (without tail pointer)?",["O(1)","O(n)","O(log n)","O(n^2)"],"O(n)","Without a tail pointer, you must traverse the entire list to find the end.","Medium","DSA","interview_reported");
add("What is the time complexity of checking if a string is a palindrome?",["O(1)","O(n)","O(n^2)","O(log n)"],"O(n)","Compare characters from both ends moving inward, O(n/2) = O(n).","Easy","DSA","interview_reported");
add("What is the difference between a stack and a queue?",["Stack is LIFO; Queue is FIFO","Stack is FIFO; Queue is LIFO","Both are FIFO","Both are LIFO"],"Stack is LIFO; Queue is FIFO","Stack removes most recently added; Queue removes oldest.","Easy","DSA","interview_reported");
add("What is the time complexity of deleting an element from the middle of an array?",["O(1)","O(log n)","O(n)","O(n^2)"],"O(n)","After deletion, all subsequent elements must be shifted left.","Easy","DSA","interview_reported");
add("Which of the following is true about a hash table?",["It guarantees O(1) worst-case lookup","It uses a hash function to compute index from key","It maintains elements in sorted order","It only stores string keys"],"It uses a hash function to compute index from key","Hash tables use a hash function to map keys to array indices.","Easy","DSA","interview_reported");
add("What is the maximum number of nodes in a binary tree of height h?",["2^h","2^(h+1) - 1","2^h - 1","h^2"],"2^(h+1) - 1","A complete binary tree of height h has at most 2^(h+1) - 1 nodes.","Medium","DSA","interview_reported");
add("What is the time complexity of searching in a balanced BST?",["O(n)","O(log n)","O(1)","O(n log n)"],"O(log n)","A balanced BST halves the search space at each step.","Medium","DSA","interview_reported");
add("What is the difference between DFS and BFS?",["DFS uses stack/recursion (depth-first); BFS uses queue (breadth-first)","They are the same","DFS is always faster","BFS uses less memory"],"DFS uses stack/recursion (depth-first); BFS uses queue (breadth-first)","DFS explores as far as possible along each branch before backtracking. BFS explores all neighbors at current depth first.","Medium","DSA","interview_reported");
add("What is the time complexity of merge sort?",["O(n)","O(n^2)","O(n log n)","O(log n)"],"O(n log n)","Merge sort divides (log n levels) and merges (n work per level).","Easy","DSA","interview_reported");
add("What is the time complexity of insertion sort in the worst case?",["O(n)","O(n log n)","O(n^2)","O(log n)"],"O(n^2)","Insertion sort shifts elements for each insertion, worst case O(n^2).","Medium","DSA","practice");
add("What is a heap data structure?",["A complete binary tree that satisfies the heap property","A sorted array","A linked list with fast access","A hash table"],"A complete binary tree that satisfies the heap property","In a max-heap, parent >= children. In a min-heap, parent <= children.","Medium","DSA","interview_reported");
add("What is the time complexity of heap insertion?",["O(1)","O(log n)","O(n)","O(n log n)"],"O(log n)","Heap insertion involves bubbling up, which takes O(log n) height of tree.","Medium","DSA","practice");
add("What is the time complexity of heap extraction (extract-min/max)?",["O(1)","O(log n)","O(n)","O(n log n)"],"O(log n)","Heap extraction replaces root and bubbles down, taking O(log n).","Medium","DSA","practice");
add("What is the difference between a min-heap and a max-heap?",["Min-heap: parent <= children; Max-heap: parent >= children","Min-heap is faster","Max-heap uses less memory","They are the same"],"Min-heap: parent <= children; Max-heap: parent >= children","Heap property determines the ordering relationship between parent and children nodes.","Easy","DSA","practice");
add("What is the time complexity of finding the kth smallest element using a min-heap?",["O(1)","O(k log n)","O(n)","O(n log n)"],"O(k log n)","Build heap O(n), then extract-min k times: O(n + k log n) = O(k log n) for k < n.","Hard","DSA","practice");
add("What is the time complexity of checking if a binary tree is balanced?",["O(1)","O(n)","O(log n)","O(n^2)"],"O(n)","Must visit each node once to check height difference, O(n).","Medium","DSA","practice");
add("What is the time complexity of reversing a linked list?",["O(1)","O(n)","O(n log n)","O(n^2)"],"O(n)","Each node is visited once, O(n).","Easy","DSA","practice");
add("What is the time complexity of detecting a cycle in a linked list using Floyd's algorithm?",["O(1)","O(n)","O(n log n)","O(n^2)"],"O(n)","Floyd's tortoise and hare algorithm visits each node at most twice.","Medium","DSA","interview_reported");
add("What is the time complexity of finding the lowest common ancestor in a BST?",["O(n)","O(log n)","O(1)","O(n log n)"],"O(log n)","BST property allows guided search from root to LCA.","Medium","DSA","practice");

// ===== SQL (15%) =====
add("Which SQL query returns the second highest salary from an Employee table?",["SELECT MAX(salary) FROM Employee WHERE salary < (SELECT MAX(salary) FROM Employee)","SELECT salary FROM Employee ORDER BY salary DESC LIMIT 1 OFFSET 1","SELECT DISTINCT salary FROM Employee ORDER BY salary DESC LIMIT 1 OFFSET 1","All of the above are valid approaches"],"All of the above are valid approaches","All three approaches find the second highest salary. DISTINCT in option C handles duplicates.","Medium","SQL","interview_reported");
add("What does the GROUP BY clause do in SQL?",["Groups rows with same values in specified columns for aggregate functions","Sorts the result set","Filters rows","Joins tables"],"Groups rows with same values in specified columns for aggregate functions","GROUP BY groups rows sharing the same values, allowing aggregate functions on each group.","Easy","SQL","interview_reported");
add("What is the difference between WHERE and HAVING?",["WHERE filters rows before grouping; HAVING filters groups after GROUP BY","They are the same","HAVING filters rows; WHERE filters groups","WHERE is used with JOIN; HAVING with SELECT"],"WHERE filters rows before grouping; HAVING filters groups after GROUP BY","WHERE applies to individual rows before GROUP BY. HAVING applies to grouped results after GROUP BY.","Easy","SQL","interview_reported");
add("What is the result of SELECT * FROM t1 LEFT JOIN t2 ON t1.id = t2.id where there is no match?",["The row is excluded","NULL values for right table columns","An error is thrown","The row is duplicated"],"NULL values for right table columns","LEFT JOIN preserves all left rows. Unmatched right columns get NULL.","Medium","SQL","interview_reported");
add("What is the difference between UNION and UNION ALL?",["UNION removes duplicates; UNION ALL keeps all rows","They are the same","UNION ALL is slower","UNION requires matching column names"],"UNION removes duplicates; UNION ALL keeps all rows","UNION automatically removes duplicate rows. UNION ALL returns all rows including duplicates.","Easy","SQL","interview_reported");
add("What does the SQL query SELECT * FROM Employees WHERE salary IS NULL return?",["Employees with salary = 0","Employees with no salary value assigned","All employees","Employees with minimum salary"],"Employees with no salary value assigned","IS NULL checks for NULL values, which represent missing or unknown data.","Easy","SQL","interview_reported");
add("What is the result of SELECT DISTINCT department FROM Employees?",["All rows from Employees","Only unique department values","The count of departments","Departments sorted alphabetically"],"Only unique department values","DISTINCT eliminates duplicate values from the result set.","Easy","SQL","interview_reported");
add("What is the result of SELECT COUNT(DISTINCT department) FROM Employees?",["Number of unique departments","Total number of employees","Total departments including duplicates","Maximum department ID"],"Number of unique departments","COUNT(DISTINCT column) counts unique non-NULL values.","Easy","SQL","interview_reported");
add("What does the HAVING clause do in SQL?",["Filters groups after GROUP BY","Filters rows before grouping","Sorts the result set","Limits the number of rows"],"Filters groups after GROUP BY","HAVING filters groups created by GROUP BY, unlike WHERE which filters rows.","Easy","SQL","interview_reported");
add("What is the result of SELECT * FROM Orders WHERE order_date BETWEEN '2024-01-01' AND '2024-12-31'?",["Orders placed in 2024","Orders placed before 2024","All orders","Orders placed after 2024"],"Orders placed in 2024","BETWEEN is inclusive on both ends.","Easy","SQL","interview_reported");
add("What is the difference between DELETE and TRUNCATE in SQL?",["DELETE removes specific rows; TRUNCATE removes all rows and resets identity","They are the same","DELETE is faster","TRUNCATE can have WHERE clause"],"DELETE removes specific rows; TRUNCATE removes all rows and resets identity","DELETE logs each row; TRUNCATE is faster with minimal logging and resets auto-increment.","Medium","SQL","interview_reported");
add("What is the result of a FULL OUTER JOIN?",["All matching rows plus unmatched from both tables","Only matching rows","All rows from left table only","All rows from right table only"],"All matching rows plus unmatched from both tables","FULL OUTER JOIN returns all rows from both tables, with NULLs where no match exists.","Medium","SQL","interview_reported");
add("What does the SQL query SELECT department, COUNT(*) FROM Employee GROUP BY department HAVING COUNT(*) > 5 return?",["All departments","Departments with more than 5 employees","Total count of employees","Departments with exactly 5 employees"],"Departments with more than 5 employees","GROUP BY groups by department, COUNT counts per group, HAVING filters groups with count > 5.","Easy","SQL","interview_reported");
add("What is the result of a LEFT JOIN when there is no matching row in the right table?",["Row excluded from result","NULL values for right table columns","Error thrown","Row duplicated"],"NULL values for right table columns","LEFT JOIN preserves all left rows; unmatched right columns get NULL.","Medium","SQL","interview_reported");
add("What does the SQL subquery SELECT * FROM Employees WHERE department_id IN (SELECT id FROM Departments WHERE location = 'NYC') return?",["All employees","Employees in departments located in NYC","All departments in NYC","Employees with salary above average"],"Employees in departments located in NYC","Inner query finds NYC department IDs. Outer query returns employees in those departments.","Medium","SQL","interview_reported");
add("What is the purpose of a subquery in SQL?",["To perform operations on the result of another query","To create indexes","To define table structure","To encrypt data"],"To perform operations on the result of another query","Subqueries (nested queries) are used within other queries to filter or compute values.","Easy","SQL","interview_reported");
add("What is the result of SELECT MAX(salary) FROM Employees?",["The highest salary value","All salaries","The employee with highest salary","The average salary"],"The highest salary value","MAX() aggregate function returns the maximum value in the column.","Easy","SQL","practice");
add("What is the difference between IN and EXISTS in SQL?",["IN checks membership in a list; EXISTS checks if a subquery returns any rows","They are always equivalent","IN is faster","EXISTS cannot use subqueries"],"IN checks membership in a list; EXISTS checks if a subquery returns any rows","IN is evaluated once; EXISTS may be more efficient with large datasets as it stops at first match.","Medium","SQL","interview_reported");
add("What is the result of SELECT * FROM Employees ORDER BY salary DESC LIMIT 3?",["Top 3 highest paid employees","Bottom 3 lowest paid employees","All employees sorted","3 random employees"],"Top 3 highest paid employees","ORDER BY DESC sorts from highest to lowest. LIMIT 3 returns only first 3 rows.","Easy","SQL","practice");
add("What is a correlated subquery?",["A subquery that references columns from the outer query","A subquery that runs independently","A subquery in the FROM clause","A subquery that returns multiple columns"],"A subquery that references columns from the outer query","Correlated subqueries execute once for each row of the outer query.","Medium","SQL","interview_reported");

// ===== DBMS (8%) =====
add("What is the result of 1NF?",["All attributes contain atomic values; no repeating groups","Table has a primary key","No partial dependencies","No transitive dependencies"],"All attributes contain atomic values; no repeating groups","1NF requires each column to hold only atomic (indivisible) values.","Easy","DBMS","interview_reported");
add("What does ACID stand for in DBMS?",["Atomicity, Consistency, Isolation, Durability","Atomicity, Concurrency, Integrity, Durability","Availability, Consistency, Isolation, Durability","Atomicity, Consistency, Integration, Durability"],"Atomicity, Consistency, Isolation, Durability","ACID properties ensure reliable database transactions.","Easy","DBMS","interview_reported");
add("What is the purpose of normalization in DBMS?",["To reduce data redundancy by decomposing tables","To increase data redundancy","To create indexes","To encrypt data"],"To reduce data redundancy by decomposing tables","Normalization organizes tables to minimize redundancy and dependency.","Easy","DBMS","interview_reported");
add("What is a foreign key?",["A column that references a primary key in another table","A unique identifier for each row","A column that cannot be NULL","An index on a table"],"A column that references a primary key in another table","Foreign key creates a link between two tables by referencing a primary key.","Easy","DBMS","interview_reported");
add("What is 2NF?",["1NF + no partial dependencies on composite primary key","1NF + no transitive dependencies","Table with no NULL values","Table with unique constraints"],"1NF + no partial dependencies on composite primary key","2NF eliminates partial dependencies where non-key attributes depend on part of a composite key.","Medium","DBMS","interview_reported");
add("What is 3NF?",["2NF + no transitive dependencies","2NF + no partial dependencies","1NF with unique constraints","2NF with composite keys"],"2NF + no transitive dependencies","3NF eliminates transitive dependencies where non-key attributes depend on other non-key attributes.","Medium","DBMS","interview_reported");
add("What is the purpose of a database index?",["To speed up data retrieval operations","To reduce storage space","To enforce data integrity","To prevent unauthorized access"],"To speed up data retrieval operations","Indexes create data structures (like B-trees) for fast lookups.","Easy","DBMS","interview_reported");
add("What is the difference between a primary key and a candidate key?",["Primary key is chosen from candidate keys; both uniquely identify rows","They are the same","Primary key can have NULLs","Candidate key must be composite"],"Primary key is chosen from candidate keys; both uniquely identify rows","A table can have multiple candidate keys; one is chosen as the primary key.","Medium","DBMS","practice");
add("What is a deadlock in DBMS?",["Two or more transactions waiting for each other to release locks","A transaction that takes too long","A corrupted database file","A table with no primary key"],"Two or more transactions waiting for each other to release locks","Deadlock occurs when transactions form a circular dependency of waiting locks.","Medium","DBMS","interview_reported");
add("What is the purpose of COMMIT in a transaction?",["To make all changes permanent","To undo all changes","To lock the database","To create a checkpoint"],"To make all changes permanent","COMMIT saves all changes made during the transaction permanently to the database.","Easy","DBMS","practice");
add("What is the purpose of ROLLBACK in a transaction?",["To undo changes made during the transaction","To save changes permanently","To lock the database","To create a backup"],"To undo changes made during the transaction","ROLLBACK reverts all changes made since the last COMMIT or SAVEPOINT.","Easy","DBMS","practice");
add("What is a B-tree index?",["A self-balancing tree data structure used for indexing","A type of hash table","A linked list with fast access","A sorted array"],"A self-balancing tree data structure used for indexing","B-trees maintain sorted data and allow searches, insertions, and deletions in O(log n).","Medium","DBMS","interview_reported");
add("What is the difference between clustered and non-clustered index?",["Clustered: physical order of rows; Non-clustered: separate structure with pointers","They are the same","Clustered is faster","Non-clustered is always better"],"Clustered: physical order of rows; Non-clustered: separate structure with pointers","Clustered index determines physical row order (one per table). Non-clustered indexes are separate structures.","Hard","DBMS","interview_reported");
add("What is referential integrity in DBMS?",["Ensuring foreign key values match primary key values in the related table","Making all columns NOT NULL","Creating unique constraints","Enforcing data types"],"Ensuring foreign key values match primary key values in the related table","Referential integrity prevents orphaned records by enforcing valid relationships.","Medium","DBMS","interview_reported");

// ===== OS (8%) =====
add("What is the difference between a process and a thread?",["Process: independent execution with own memory; Thread: lightweight, shares memory","They are the same","Thread is heavier than a process","Process cannot have multiple threads"],"Process: independent execution with own memory; Thread: lightweight, shares memory","Processes have separate address spaces; threads within a process share memory.","Easy","OS","interview_reported");
add("What are the four conditions required for deadlock?",["Mutual exclusion, Hold and wait, No preemption, Circular wait","Mutual exclusion, Hold and wait, Preemption, Circular wait","Shared resources, Hold and wait, No preemption, No circular wait","Mutual exclusion, Release and wait, No preemption, Circular wait"],"Mutual exclusion, Hold and wait, No preemption, Circular wait","All four Coffman conditions must hold simultaneously for deadlock.","Medium","OS","interview_reported");
add("What is the difference between concurrency and parallelism?",["Concurrency: overlapping time periods; Parallel: simultaneous on multiple cores","They are the same","Parallel is a subset of concurrent","Concurrency requires multiple cores"],"Concurrency: overlapping time periods; Parallel: simultaneous on multiple cores","Concurrency is dealing with multiple tasks at once; parallelism is doing them at once.","Medium","OS","interview_reported");
add("What is a semaphore in OS?",["A synchronization primitive for controlling access to shared resources","A type of thread","A memory management technique","A scheduling algorithm"],"A synchronization primitive for controlling access to shared resources","Semaphores use a counter to manage access to resources by multiple processes/threads.","Medium","OS","interview_reported");
add("What is virtual memory?",["Using disk space as an extension of RAM to run programs larger than physical memory","A type of cache","A virtual machine","An encrypted memory region"],"Using disk space as an extension of RAM to run programs larger than physical memory","Virtual memory allows programs to use more memory than physically available by swapping to disk.","Easy","OS","interview_reported");
add("What is the difference between paging and segmentation?",["Paging: fixed-size blocks; Segmentation: variable-size blocks based on logical division","They are the same","Paging is faster","Segmentation uses fixed blocks"],"Paging: fixed-size blocks; Segmentation: variable-size blocks based on logical division","Paging divides memory into fixed pages; segmentation divides by logical units (segments).","Medium","OS","interview_reported");
add("What is a race condition?",["When multiple threads access shared data concurrently and the outcome depends on timing","A type of deadlock","A memory leak","A scheduling error"],"When multiple threads access shared data concurrently and the outcome depends on timing","Race conditions occur when concurrent operations on shared data produce unpredictable results.","Medium","OS","interview_reported");
add("What is the Round Robin scheduling algorithm?",["Each process gets a fixed time slice in cyclic order","Processes are scheduled by priority","Longest job first","Shortest job first"],"Each process gets a fixed time slice in cyclic order","Round Robin assigns time quanta to processes in a circular fashion, ensuring fairness.","Easy","OS","interview_reported");
add("What is the difference between a mutex and a semaphore?",["Mutex: binary lock for one thread; Semaphore: counter for multiple threads","They are the same","Mutex is faster","Semaphore is binary"],"Mutex: binary lock for one thread; Semaphore: counter for multiple threads","Mutex provides mutual exclusion for a single resource. Semaphore can allow multiple concurrent accesses up to a count.","Medium","OS","interview_reported");
add("What is thrashing in OS?",["Excessive paging where the system spends more time swapping than executing","A type of deadlock","CPU overheating","Memory overflow"],"Excessive paging where the system spends more time swapping than executing","Thrashing occurs when the working set exceeds available memory, causing constant page faults.","Hard","OS","interview_reported");
add("What is context switching?",["Saving the state of one process and restoring another's state","Switching between virtual machines","Changing the CPU clock speed","Loading a new program"],"Saving the state of one process and restoring another's state","Context switching allows the CPU to share between multiple processes by saving/restoring their states.","Easy","OS","practice");
add("What is a zombie process?",["A process that has terminated but its parent hasn't read its exit status","A process that consumes no resources","A process running in background","A corrupted process"],"A process that has terminated but its parent hasn't read its exit status","Zombie processes hold a PID entry until the parent calls wait() to collect exit status.","Medium","OS","practice");

// ===== NETWORKING (5%) =====
add("What is the difference between TCP and UDP?",["TCP: connection-oriented, reliable; UDP: connectionless, faster","They are the same","UDP is more reliable","TCP is faster"],"TCP: connection-oriented, reliable; UDP: connectionless, faster","TCP establishes connections and guarantees delivery. UDP sends without connection setup.","Easy","Networking","interview_reported");
add("Which HTTP status code indicates a resource was not found?",["200","301","404","500"],"404","404 Not Found indicates the server could not find the requested resource.","Easy","Networking","interview_reported");
add("Which layer of the OSI model is responsible for routing packets?",["Data Link Layer","Network Layer","Transport Layer","Session Layer"],"Network Layer","The Network Layer (Layer 3) handles routing, forwarding, and addressing.","Easy","Networking","interview_reported");
add("What is the difference between HTTP and HTTPS?",["HTTPS uses SSL/TLS encryption; HTTP sends data in plain text","HTTP is faster","HTTPS does not use ports","They are the same"],"HTTPS uses SSL/TLS encryption; HTTP sends data in plain text","HTTPS adds TLS/SSL encryption for secure communication.","Easy","Networking","interview_reported");
add("What does DNS do?",["Resolves domain names to IP addresses","Encrypts network traffic","Routes packets between networks","Manages email delivery"],"Resolves domain names to IP addresses","DNS translates human-readable domain names to machine-readable IP addresses.","Easy","Networking","interview_reported");
add("What is a three-way handshake in TCP?",["SYN -> SYN-ACK -> ACK to establish a connection","Data transfer method","Connection termination","Error recovery method"],"SYN -> SYN-ACK -> ACK to establish a connection","TCP uses three-way handshake to establish a reliable connection before data transfer.","Medium","Networking","interview_reported");
add("What is the purpose of a load balancer?",["Distributes incoming network traffic across multiple servers","Encrypts data","Stores backup data","Monitors network traffic"],"Distributes incoming network traffic across multiple servers","Load balancers ensure no single server is overwhelmed, improving availability and reliability.","Easy","Networking","practice");
add("What is the difference between ARP and RARP?",["ARP: IP to MAC; RARP: MAC to IP","They are the same","ARP is faster","RARP is deprecated"],"ARP: IP to MAC; RARP: MAC to IP","ARP resolves IP addresses to MAC addresses. RARP does the reverse (largely replaced by DHCP).","Medium","Networking","practice");

// ===== CLOUD & WEB (5%) =====
add("What is the difference between IaaS, PaaS, and SaaS?",["IaaS: infrastructure; PaaS: platform for development; SaaS: software as service","They are the same","IaaS is the most managed","SaaS requires most management"],"IaaS: infrastructure; PaaS: platform for development; SaaS: software as service","IaaS provides raw infrastructure. PaaS provides development platform. SaaS provides complete software.","Easy","Cloud","interview_reported");
add("What is a REST API?",["An architectural style for designing networked applications using HTTP methods","A database query language","A programming language","A type of firewall"],"An architectural style for designing networked applications using HTTP methods","REST uses HTTP methods (GET, POST, PUT, DELETE) and stateless communication.","Easy","Cloud","interview_reported");
add("What does JSON stand for?",["JavaScript Object Notation","Java Serialized Object Notion","JavaScript Online Notation","Java Standard Object Name"],"JavaScript Object Notation","JSON is a lightweight data interchange format based on JavaScript object syntax.","Easy","Cloud","practice");
add("What is the difference between GET and POST HTTP methods?",["GET: retrieves data; POST: sends data to create/update","They are the same","GET is more secure","POST is faster"],"GET: retrieves data; POST: sends data to create/update","GET appends data to URL; POST sends data in request body. GET is cacheable; POST is not.","Easy","Cloud","interview_reported");
add("What is the difference between horizontal and vertical scaling?",["Horizontal: add more machines; Vertical: add more power to existing machine","They are the same","Horizontal is always better","Vertical is cheaper"],"Horizontal: add more machines; Vertical: add more power to existing machine","Horizontal scaling (scaling out) adds nodes. Vertical scaling (scaling up) increases resources on a single node.","Medium","Cloud","interview_reported");
add("What is containerization?",["Packaging applications with their dependencies for consistent deployment","Virtual machine technology","Database management","Network configuration"],"Packaging applications with their dependencies for consistent deployment","Containers (like Docker) package code and dependencies together for consistent运行 across environments.","Easy","Cloud","practice");
add("What is microservices architecture?",["Application composed of small, independent services communicating via APIs","A single monolithic application","A database design pattern","A testing framework"],"Application composed of small, independent services communicating via APIs","Microservices break applications into loosely coupled, independently deployable services.","Medium","Cloud","interview_reported");
add("What is the difference between public, private, and hybrid cloud?",["Public: shared infrastructure; Private: dedicated; Hybrid: combination","They are the same","Public is more secure","Private is cheaper"],"Public: shared infrastructure; Private: dedicated; Hybrid: combination","Public cloud is shared (AWS, Azure). Private cloud is dedicated. Hybrid combines both.","Easy","Cloud","interview_reported");

// ===== MORE PROGRAMMING (remaining to hit 200+) =====
add("What is the output of this code?\nint x = 5;\nprintf(\"%d\", x++ + x++);",["10","11","21","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 5;\nprintf(\"%d\", x-- + x--);",["10","9","21","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 5;\nprintf(\"%d\", x++ - x--);",["0","1","Undefined behavior","10"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 5;\nprintf(\"%d\", ++x + x++);",["11","12","10","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 3;\nprintf(\"%d\", x++ + x++ + x++);",["9","10","18","Undefined behavior"],"Undefined behavior","Modifying x three times between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 3;\nprintf(\"%d\", ++x + ++x);",["7","8","6","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 4;\nprintf(\"%d\", x-- - --x);",["6","4","Undefined behavior","2"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 4;\nprintf(\"%d\", x-- + --x);",["6","8","Undefined behavior","4"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", x++ + ++x);",["20","22","21","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", ++x + x++);",["21","22","20","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", x++ - x--);",["0","1","Undefined behavior","20"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", x-- - --x);",["18","20","Undefined behavior","0"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", x-- + --x);",["18","20","Undefined behavior","2"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", --x + x--);",["18","20","Undefined behavior","0"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", --x + --x);",["18","20","16","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", ++x - x++);",["0","1","20","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", ++x - ++x);",["0","2","20","Undefined behavior"],"Undefined behavior","Modifying x twice between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", x++ + x++ + x++);",["30","33","31","Undefined behavior"],"Undefined behavior","Modifying x three times between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", ++x + ++x + ++x);",["33","30","36","Undefined behavior"],"Undefined behavior","Modifying x three times between sequence points is undefined behavior.","Hard","Programming","interview_reported");
add("What is the output of this code?\nint x = 10;\nprintf(\"%d\", x++ + ++x + x++);",["32","33","31","Undefined behavior"],"Undefined behavior","Modifying x three times between sequence points is undefined behavior.","Hard","Programming","interview_reported");

// ===== MORE OOP (to reach 200+) =====
add("What is the output of this Java code?\nclass A { { System.out.print(\"Init\"); } }\nnew A();",["Init","Compilation error","Runtime error","Nothing"],"Init","Instance initializer block runs when an object is created, before the constructor.","Medium","OOP","practice");
add("What is the output?\nclass Test { Test() { System.out.print(\"T\"); } }\nTest t1 = new Test();\nTest t2 = new Test();",["TT","T","TTT","Error"],"TT","Each new Test() calls the constructor. Two objects = two constructor calls.","Easy","OOP","practice");
add("What is the difference between 'this' and 'super' in Java?",["this refers to current object; super refers to parent object","They are the same","this is static; super is instance","super is used only in interfaces"],"this refers to current object; super refers to parent object","this accesses current class members; super accesses parent class members.","Easy","OOP","practice");
add("What is the output of this code?\nclass Parent { void show() { System.out.println(\"Parent\"); } }\nclass Child extends Parent { void show() { System.out.println(\"Child\"); } }\nParent p = new Child();\np.show();",["Parent","Child","Compilation error","Runtime error"],"Child","Method overriding: runtime type determines which method is called.","Easy","OOP","interview_reported");
add("Can an interface have a constructor in Java?",["No, interfaces cannot have constructors","Yes, but it must be public","Yes, it can be abstract","Only default interfaces can"],"No, interfaces cannot have constructors","Interfaces cannot have constructors because they cannot be instantiated directly.","Easy","OOP","practice");
add("What is the output?\nclass A { int x = 10; }\nclass B extends A { int x = 20; void show() { System.out.println(super.x); } }\nnew B().show();",["10","20","Compilation error","30"],"10","super.x accesses the parent class's x value (10).","Medium","OOP","practice");
add("What is dependency injection in OOP?",["Providing an object's dependencies from outside rather than creating them internally","Creating objects inside a method","Using static methods","Inheriting from multiple classes"],"Providing an object's dependencies from outside rather than creating them internally","DI promotes loose coupling by injecting dependencies rather than hardcoding them.","Medium","OOP","practice");
add("What is the Liskov Substitution Principle?",["Objects of a superclass should be replaceable with objects of a subclass without breaking functionality","A class should have only one reason to change","Classes should depend on interfaces, not concrete classes","A subclass should not override parent methods incorrectly"],"Objects of a superclass should be replaceable with objects of a subclass without breaking functionality","LSP ensures that inheritance hierarchies maintain behavioral compatibility.","Hard","OOP","interview_reported");

// ===== MORE DSA =====
add("What is the time complexity of finding the maximum element in an unsorted array?",["O(1)","O(log n)","O(n)","O(n^2)"],"O(n)","Must check every element to find maximum, O(n).","Easy","DSA","practice");
add("What is the time complexity of reversing an array?",["O(1)","O(n)","O(n log n)","O(n^2)"],"O(n)","Each element is visited once during reversal.","Easy","DSA","practice");
add("What is the time complexity of counting occurrences of an element in a sorted array?",["O(n)","O(log n)","O(n log n)","O(1)"],"O(n)","Even in sorted array, you must scan for all occurrences. Binary search finds one, but counting all is O(n).","Medium","DSA","practice");
add("What is the time complexity of finding a pair with a given sum in a sorted array (two pointers)?",["O(n^2)","O(n)","O(log n)","O(n log n)"],"O(n)","Two pointers approach: start and end pointers move inward, O(n).","Medium","DSA","practice");
add("What is the time complexity of rotating an array by k positions?",["O(1)","O(n)","O(k)","O(n^2)"],"O(n)","Must visit each element once for the rotation.","Easy","DSA","practice");
add("What is the time complexity of merging two sorted arrays?",["O(n)","O(m+n)","O(n log n)","O(m*n)"],"O(m+n)","Each element from both arrays is visited once.","Easy","DSA","practice");
add("What is the time complexity of checking if two strings are anagrams (sorting approach)?",["O(n)","O(n log n)","O(n^2)","O(1)"],"O(n log n)","Sort both strings O(n log n) then compare O(n). Overall O(n log n).","Medium","DSA","practice");
add("What is the time complexity of finding the kth largest element using a min-heap of size k?",["O(n)","O(k log n)","O(n log n)","O(k)"],"O(k log n)","Build heap O(k), then iterate remaining elements: O((n-k) log k). Overall O(n log k).","Hard","DSA","practice");
add("What is the time complexity of checking if a number is prime (trial division)?",["O(1)","O(log n)","O(sqrt(n))","O(n)"],"O(sqrt(n))","Check divisibility up to sqrt(n).","Medium","DSA","interview_reported");
add("What is the time complexity of generating Fibonacci numbers using recursion (without memoization)?",["O(n)","O(2^n)","O(n^2)","O(log n)"],"O(2^n)","Without memoization, recursive Fibonacci has exponential time complexity.","Hard","DSA","interview_reported");
add("What is the time complexity of checking if a linked list has a cycle (Floyd's)?",["O(1)","O(n)","O(n log n)","O(n^2)"],"O(n)","Floyd's algorithm visits each node at most twice.","Medium","DSA","interview_reported");
add("What is the time complexity of finding the length of a linked list?",["O(1)","O(n)","O(log n)","O(n^2)"],"O(n)","Must traverse the entire list to count nodes.","Easy","DSA","practice");

const outPath = path.join(__dirname, '../../data/companyMock/deloitte/mcq.json');
fs.writeFileSync(outPath, JSON.stringify(mcqs, null, 2), 'utf8');
console.log(`Written ${mcqs.length} MCQs to ${outPath}`);

// Verify
const diff = {};
mcqs.forEach(q => diff[q.difficulty] = (diff[q.difficulty]||0)+1);
console.log('Difficulty:', diff);
const topics = {};
mcqs.forEach(q => topics[q.topic] = (topics[q.topic]||0)+1);
console.log('Topics:', topics);
