import mongoose from "mongoose";

const systemConfigSchema = new mongoose.Schema({
  key: { type: String, required: true, unique: true, trim: true },
  value: { type: mongoose.Schema.Types.Mixed, required: true },
  label: { type: String, default: "" },
  description: { type: String, default: "" },
  type: {
    type: String,
    enum: ["string", "number", "boolean", "select", "color", "text"],
    default: "string",
  },
  options: [{ type: String }],
  category: {
    type: String,
    enum: ["general", "test", "theme", "report", "email", "security"],
    default: "general",
  },
}, { timestamps: true });

const SystemConfig = mongoose.model("SystemConfig", systemConfigSchema);

export async function getConfig(key, defaultValue = null) {
  const config = await SystemConfig.findOne({ key }).lean();
  return config ? config.value : defaultValue;
}

export async function setConfig(key, value) {
  return SystemConfig.findOneAndUpdate(
    { key },
    { $set: { value } },
    { upsert: true, new: true }
  );
}

export const DEFAULT_CONFIGS = [
  { key: "maxTestAttempts", value: 3, label: "Maximum Test Attempts", type: "number", category: "test", description: "Default max attempts per test" },
  { key: "defaultPassingMarks", value: 40, label: "Default Passing Marks (%)", type: "number", category: "test", description: "Default passing percentage" },
  { key: "defaultDuration", value: 30, label: "Default Duration (min)", type: "number", category: "test", description: "Default test duration in minutes" },
  { key: "defaultTheme", value: "light", label: "Default Theme", type: "select", options: ["light", "dark"], category: "theme", description: "System default theme" },
  { key: "companyLogo", value: "", label: "Company Logo URL", type: "string", category: "theme", description: "Logo shown on reports" },
  { key: "collegeLogo", value: "", label: "College Logo URL", type: "string", category: "theme", description: "College logo on PDF reports" },
  { key: "reportHeader", value: "AI Interview Platform - Performance Report", label: "Report Header Text", type: "string", category: "report", description: "Header text on PDF reports" },
  { key: "reportFooter", value: "Generated by AI Interview Platform", label: "Report Footer Text", type: "string", category: "report", description: "Footer text on PDF reports" },
  { key: "smtpConfigured", value: false, label: "SMTP Configured", type: "boolean", category: "email", description: "Whether email sending is configured" },
  { key: "rateLimitingEnabled", value: true, label: "Rate Limiting", type: "boolean", category: "security", description: "Enable API rate limiting" },
];

export default SystemConfig;
