/**
 * testInterviewJudgeEngine.js
 * ===========================
 * Comprehensive 55+ Test Suite for InterviewJudgeEngine.
 * Covers Golden Tests, Real Bug Regressions, Technical Domains, HR, and Project.
 */

import { judgeAnswer, judgeQuestionBatch } from "../services/realInterviewAI/interviewJudgeEngine.js";

console.log("================================================================================");
console.log("             TESTING UNIFIED INTERVIEW JUDGE ENGINE (55+ CASES)                ");
console.log("================================================================================\n");

const TEST_CASES = [
  // =========================================================================
  // 1. GOLDEN TESTS & ANSWER GATE REGRESSION
  // =========================================================================
  {
    id: "G_01",
    category: "GOLDEN / CLI",
    domain: "Git",
    question: "What command shows the current Git status?",
    expectedKnowledge: "Use git status to display working directory and staging area status.",
    candidateAnswer: "git status",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "G_02",
    category: "GOLDEN / SYNONYM ALIGNMENT",
    domain: "Java",
    question: "What is a final class in Java?",
    expectedKnowledge: "A final class cannot be extended or inherited by any other class.",
    candidateAnswer: "Subclassing is prohibited for final classes.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "CORRECT",
    minScore: 4,
    maxScore: 5,
  },
  {
    id: "G_03",
    category: "GOLDEN / REFUSAL GATE",
    domain: "Java",
    question: "What is a final class in Java?",
    expectedKnowledge: "A final class cannot be extended.",
    candidateAnswer: "I cannot answer this question.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },
  {
    id: "G_04",
    category: "GOLDEN / FILLER GATE",
    domain: "Java",
    question: "What is a final class in Java?",
    expectedKnowledge: "A final class cannot be extended.",
    candidateAnswer: "Thank you.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },
  {
    id: "G_05",
    category: "GOLDEN / SHORT FACT",
    domain: "HTTP",
    question: "What does HTTP 404 mean?",
    expectedKnowledge: "HTTP status code 404 means the requested resource was not found on the server.",
    candidateAnswer: "404 means the requested resource was not found.",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "G_06",
    category: "GOLDEN / SQL",
    domain: "SQL",
    question: "Write an SQL query to retrieve all records from the Products table.",
    expectedKnowledge: "SELECT * FROM Products;",
    candidateAnswer: "SELECT * FROM Products;",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "G_07",
    category: "GOLDEN / UNRELATED",
    domain: "General Tech",
    question: "What is polymorphism in Object-Oriented Programming?",
    expectedKnowledge: "Polymorphism is the ability of an object or method to take on many forms.",
    candidateAnswer: "Install Photoshop to edit images with filters.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },
  {
    id: "G_08",
    category: "GOLDEN / PARTIAL CONCEPT",
    domain: "Java",
    question: "What are the effects of the final keyword in Java?",
    expectedKnowledge: "A final class cannot be extended, a final method cannot be overridden, and a final variable cannot be reassigned.",
    candidateAnswer: "A final class cannot be extended.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "PARTIALLY_CORRECT",
    minScore: 2,
    maxScore: 3,
  },
  {
    id: "G_09",
    category: "GOLDEN / HR NO STAR",
    domain: "HR",
    question: "Introduce yourself.",
    expectedKnowledge: "Candidate should outline education, key technical stack, top projects, and career enthusiasm.",
    candidateAnswer: "I am a Computer Science graduate from ABC University. I specialize in React and Node.js backend services and built an e-commerce platform.",
    maxMarks: 20,
    difficulty: "easy",
    round: "hr",
    expectedStatus: "CORRECT",
    minScore: 16,
    maxScore: 20,
  },
  {
    id: "G_10",
    category: "GOLDEN / GENERAL HR FREE-MARK PREVENTION",
    domain: "HR",
    question: "How do you approach team accountability and professional ethics?",
    expectedKnowledge: "Maintain transparent communication, own up to mistakes, and adhere to industry standards.",
    candidateAnswer: "I work with my team because of work in the project.",
    maxMarks: 20,
    difficulty: "medium",
    round: "hr",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },
  {
    id: "G_11",
    category: "REAL BUG REGRESSION",
    domain: "Technical",
    question: "Explain the virtual DOM in React.",
    expectedKnowledge: "Virtual DOM is a lightweight in-memory representation of real DOM that React diffs to optimize updates.",
    candidateAnswer: "I cannot answer these questions. Sorry for that.",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },

  // =========================================================================
  // 2. EMPTY, REFUSAL & FILLER GATING (A)
  // =========================================================================
  {
    id: "A_01",
    category: "EMPTY / WHITESPACE",
    domain: "General",
    question: "What is an index in SQL?",
    expectedKnowledge: "An index is a database structure that improves search query performance.",
    candidateAnswer: "   ",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "NOT_ATTEMPTED",
    expectedScore: 0,
  },
  {
    id: "A_02",
    category: "PLACEHOLDER",
    domain: "General",
    question: "What is an index in SQL?",
    expectedKnowledge: "An index is a database structure that improves search query performance.",
    candidateAnswer: "(No answer submitted)",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "NOT_ATTEMPTED",
    expectedScore: 0,
  },
  {
    id: "A_03",
    category: "REFUSAL / DON'T KNOW",
    domain: "General",
    question: "What is an index in SQL?",
    expectedKnowledge: "An index is a database structure that improves search query performance.",
    candidateAnswer: "I don't know the answer to this question, sorry.",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },
  {
    id: "A_04",
    category: "REFUSAL / SKIP",
    domain: "General",
    question: "What is an index in SQL?",
    expectedKnowledge: "An index is a database structure that improves search query performance.",
    candidateAnswer: "Please skip to next question.",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },

  // =========================================================================
  // 3. SHORT EXACT & KEYWORD ANSWERS (B & I)
  // =========================================================================
  {
    id: "B_01",
    category: "SHORT EXACT / KEYWORD",
    domain: "Python",
    question: "What keyword defines a function in Python?",
    expectedKnowledge: "The def keyword is used to define functions in Python.",
    candidateAnswer: "def",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "B_02",
    category: "SHORT EXACT / PROTOCOL",
    domain: "Networking",
    question: "Which transport protocol provides reliable, connection-oriented data transmission?",
    expectedKnowledge: "TCP provides connection-oriented, reliable byte stream delivery.",
    candidateAnswer: "TCP",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "B_03",
    category: "SHORT EXACT / CODE",
    domain: "Python",
    question: "How do you initialize an empty list in Python?",
    expectedKnowledge: "my_list = [] or my_list = list()",
    candidateAnswer: "my_list = []",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "B_04",
    category: "SHORT EXACT / OUTPUT",
    domain: "Python",
    question: "What is the output of print(2 ** 3)?",
    expectedKnowledge: "8",
    candidateAnswer: "8",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "B_05",
    category: "SHORT EXACT / COMPLEXITY",
    domain: "Algorithms",
    question: "What is the average time complexity of searching in a balanced binary search tree?",
    expectedKnowledge: "O(log n)",
    candidateAnswer: "O(log n)",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },

  // =========================================================================
  // 4. CLI, LINUX, DOCKER & GIT (N)
  // =========================================================================
  {
    id: "N_01",
    category: "CLI / GIT",
    domain: "Git",
    question: "What Git command creates and switches to a new branch called 'dev'?",
    expectedKnowledge: "git checkout -b dev or git switch -c dev",
    candidateAnswer: "git checkout -b dev",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "N_02",
    category: "CLI / LINUX",
    domain: "Linux",
    question: "What command grants read, write, and execute permissions to the owner and read/execute to others for file 'run.sh'?",
    expectedKnowledge: "chmod 755 run.sh",
    candidateAnswer: "chmod 755 run.sh",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "N_03",
    category: "CLI / DOCKER",
    domain: "Docker",
    question: "What command runs an Nginx container in background detached mode mapping port 80 to 80?",
    expectedKnowledge: "docker run -d -p 80:80 nginx",
    candidateAnswer: "docker run -d -p 80:80 nginx",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },

  // =========================================================================
  // 5. CONTRADICTION DETECTION (H)
  // =========================================================================
  {
    id: "H_01",
    category: "CONTRADICTION",
    domain: "HTTP",
    question: "Explain the HTTP GET method.",
    expectedKnowledge: "HTTP GET is safe and read-only, used to retrieve data without side effects.",
    candidateAnswer: "HTTP GET deletes and destroys the user account on the server.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },
  {
    id: "H_02",
    category: "CONTRADICTION",
    domain: "Databases",
    question: "What is Redis and what is it used for?",
    expectedKnowledge: "Redis is an in-memory key-value cache used for fast read access and session caching.",
    candidateAnswer: "Redis is a relational SQL database used to permanently store critical transactional financial records.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },
  {
    id: "H_03",
    category: "CONTRADICTION",
    domain: "Java",
    question: "Can a final class be extended in Java?",
    expectedKnowledge: "No, a final class cannot be extended or inherited.",
    candidateAnswer: "Final classes can be extended to allow extensive subclassing and inheritance hierarchies.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },
  {
    id: "H_04",
    category: "CONTRADICTION",
    domain: "Networking",
    question: "What is the difference between TCP and UDP?",
    expectedKnowledge: "TCP is connection-oriented and reliable, while UDP is connectionless and unreliable.",
    candidateAnswer: "TCP is connectionless and unreliable, whereas UDP is connection-oriented and guarantees delivery.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },

  // =========================================================================
  // 6. JAVASCRIPT, REACT & NODE.JS (L & M)
  // =========================================================================
  {
    id: "L_01",
    category: "CONCEPTUAL",
    domain: "Node.js",
    question: "Explain the Node.js event loop.",
    expectedKnowledge: "Node.js event loop handles non-blocking asynchronous I/O operations via callbacks, timers, and worker threads.",
    candidateAnswer: "The event loop enables non-blocking asynchronous operations by delegating I/O tasks and executing callbacks when operations complete.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "CORRECT",
    minScore: 4,
    maxScore: 5,
  },
  {
    id: "M_01",
    category: "CONCEPTUAL",
    domain: "React",
    question: "What is the difference between props and state in React?",
    expectedKnowledge: "Props are immutable parameters passed from parent to child, while state is mutable data managed locally within the component.",
    candidateAnswer: "Props are read-only inputs passed to components, while state is component-managed internal data that triggers re-renders on change.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "CORRECT",
    minScore: 4,
    maxScore: 5,
  },
  {
    id: "M_02",
    category: "CONCEPTUAL",
    domain: "React",
    question: "Why do we use the useEffect hook in React?",
    expectedKnowledge: "useEffect handles side effects such as data fetching, subscriptions, and DOM mutations in functional components.",
    candidateAnswer: "useEffect manages side effects like fetching API data and subscribing to events after render.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "CORRECT",
    minScore: 4,
    maxScore: 5,
  },

  // =========================================================================
  // 7. ARCHITECTURE & SYSTEM DESIGN (Q)
  // =========================================================================
  {
    id: "Q_01",
    category: "ARCHITECTURE / FULL CREDIT",
    domain: "Cloud / AWS",
    question: "Design a highly available and scalable web application architecture on AWS.",
    expectedKnowledge: "Deploy stateless compute across multiple AZs with ALB, Multi-AZ database, caching, and CDN.",
    candidateAnswer: "Deploy stateless web instances in an Auto Scaling group across multiple Availability Zones behind an Application Load Balancer. Use Multi-AZ RDS for automated database failover, Redis for caching, and CloudFront CDN for static assets.",
    maxMarks: 13,
    difficulty: "hard",
    round: "technical",
    expectedStatus: "CORRECT",
    minScore: 11,
    maxScore: 13,
  },
  {
    id: "Q_02",
    category: "ARCHITECTURE / PARTIAL CREDIT",
    domain: "Cloud / AWS",
    question: "Design a highly available and scalable web application architecture on AWS.",
    expectedKnowledge: "Deploy stateless compute across multiple AZs with ALB, Multi-AZ database, caching, and CDN.",
    candidateAnswer: "We can use an Application Load Balancer with EC2 instances.",
    maxMarks: 13,
    difficulty: "hard",
    round: "technical",
    expectedStatus: "PARTIALLY_CORRECT",
    minScore: 4,
    maxScore: 8,
  },

  // =========================================================================
  // 8. HR EVALUATION (S, T, U, V)
  // =========================================================================
  {
    id: "S_01",
    category: "HR INTRODUCTION",
    domain: "HR",
    question: "Tell me about yourself.",
    expectedKnowledge: "State education, core technical stack, key projects built, and career enthusiasm.",
    candidateAnswer: "I graduated with a Computer Science degree from XYZ Institute. I have worked extensively with Python and React building full-stack applications.",
    maxMarks: 20,
    difficulty: "easy",
    round: "hr",
    expectedStatus: "CORRECT",
    minScore: 16,
    maxScore: 20,
  },
  {
    id: "T_01",
    category: "HR BEHAVIORAL / STAR",
    domain: "HR",
    question: "Describe a situation where you had a conflict with a team member and how you resolved it.",
    expectedKnowledge: "Describe situation, proactive action with personal accountability, and positive resolution.",
    candidateAnswer: "In our final year project, we had a conflict over whether to use SQL or NoSQL. I scheduled a discussion, presented a benchmark comparison of our transactional requirements, and we agreed to use PostgreSQL. As a result, we delivered the project on time with zero schema inconsistencies.",
    maxMarks: 20,
    difficulty: "medium",
    round: "hr",
    expectedStatus: "CORRECT",
    minScore: 17,
    maxScore: 20,
  },
  {
    id: "T_02",
    category: "HR BEHAVIORAL / INCOMPLETE",
    domain: "HR",
    question: "Describe a situation where you had a conflict with a team member and how you resolved it.",
    expectedKnowledge: "Describe situation, proactive action with personal accountability, and positive resolution.",
    candidateAnswer: "There was a conflict in our group.",
    maxMarks: 20,
    difficulty: "medium",
    round: "hr",
    expectedStatus: "PARTIALLY_CORRECT",
    minScore: 4,
    maxScore: 8,
  },
  {
    id: "U_01",
    category: "HR STRENGTHS",
    domain: "HR",
    question: "What are your greatest strengths?",
    expectedKnowledge: "Identify 1-2 core strengths backed by practical examples.",
    candidateAnswer: "My greatest strengths are rapid learning and systematic debugging. When learning new libraries, I read docs thoroughly and solve issues methodically.",
    maxMarks: 20,
    difficulty: "easy",
    round: "hr",
    expectedStatus: "CORRECT",
    minScore: 16,
    maxScore: 20,
  },
  {
    id: "U_02",
    category: "HR WEAKNESS",
    domain: "HR",
    question: "What is your biggest weakness and how do you work on it?",
    expectedKnowledge: "State a genuine weakness and actionable mitigation steps.",
    candidateAnswer: "I used to struggle with public speaking. To address this, I volunteered to present sprint demos and practiced regularly, which improved my confidence.",
    maxMarks: 20,
    difficulty: "easy",
    round: "hr",
    expectedStatus: "CORRECT",
    minScore: 16,
    maxScore: 20,
  },
  {
    id: "V_01",
    category: "HR MOTIVATION",
    domain: "HR",
    question: "Why should we hire you for this role?",
    expectedKnowledge: "Highlight relevant technical skills, rapid learning capability, and contribution to team.",
    candidateAnswer: "You should hire me because I bring strong fundamentals in React and Node.js, a dedicated work ethic, and the ability to learn and contribute to team goals immediately.",
    maxMarks: 20,
    difficulty: "easy",
    round: "hr",
    expectedStatus: "CORRECT",
    minScore: 16,
    maxScore: 20,
  },
  {
    id: "V_02",
    category: "HR CAREER GOALS",
    domain: "HR",
    question: "Where do you see yourself in the next 3-5 years?",
    expectedKnowledge: "Outline a clear trajectory towards technical depth, system architecture, and mentoring.",
    candidateAnswer: "In the next 3-5 years, I aim to master cloud architecture, take ownership of critical backend services, and mentor junior developers.",
    maxMarks: 20,
    difficulty: "easy",
    round: "hr",
    expectedStatus: "CORRECT",
    minScore: 16,
    maxScore: 20,
  },

  // =========================================================================
  // 9. PROJECT EVALUATION (W & X)
  // =========================================================================
  {
    id: "W_01",
    category: "PROJECT ARCHITECTURE",
    domain: "Project",
    question: "Explain the communication architecture between your React frontend and Spring Boot backend.",
    expectedKnowledge: "React calls REST APIs exposed by Spring Boot controllers, services handle business logic, and repositories communicate with the database.",
    candidateAnswer: "React calls REST APIs exposed by the Spring Boot backend, controllers receive requests, services handle business logic, and repositories communicate with the database.",
    maxMarks: 10,
    difficulty: "medium",
    round: "project",
    expectedStatus: "CORRECT",
    minScore: 9,
    maxScore: 10,
  },
  {
    id: "W_02",
    category: "PROJECT ARCHITECTURE / VAGUE",
    domain: "Project",
    question: "Explain the communication architecture between your React frontend and Spring Boot backend.",
    expectedKnowledge: "React calls REST APIs exposed by Spring Boot controllers, services handle business logic, and repositories communicate with the database.",
    candidateAnswer: "Frontend calls backend and backend calls database.",
    maxMarks: 10,
    difficulty: "medium",
    round: "project",
    expectedStatus: "PARTIALLY_CORRECT",
    minScore: 2,
    maxScore: 5,
  },
  {
    id: "X_01",
    category: "PROJECT IMPLEMENTATION / AUTH",
    domain: "Project",
    question: "How did you implement secure user authentication in your project?",
    expectedKnowledge: "Passwords were encrypted with bcrypt, login returns signed JWT access tokens verified via backend authentication middleware.",
    candidateAnswer: "We hashed user passwords using bcrypt with salt rounds. Upon login, the backend signs a JWT access token which is passed in the Authorization header and verified by Express auth middleware on protected routes.",
    maxMarks: 10,
    difficulty: "medium",
    round: "project",
    expectedStatus: "CORRECT",
    minScore: 9,
    maxScore: 10,
  },
  {
    id: "X_02",
    category: "PROJECT IMPLEMENTATION / CACHING",
    domain: "Project",
    question: "How did you handle performance optimization and caching in your project?",
    expectedKnowledge: "Used Redis in-memory cache to store frequent database query results with a TTL expiration policy.",
    candidateAnswer: "We integrated Redis caching for high-traffic read queries with a 15-minute TTL, reducing database load and speeding up API response times.",
    maxMarks: 10,
    difficulty: "medium",
    round: "project",
    expectedStatus: "CORRECT",
    minScore: 9,
    maxScore: 10,
  },

  // =========================================================================
  // 10. EXPANDED DOMAIN & CATEGORY COVERAGE (C, D, E, F, I, J, K, O, P, R)
  // =========================================================================
  {
    id: "C_01",
    category: "SHORT SEMANTIC / OOP",
    domain: "Java",
    question: "Can a private method in Java be overridden by a subclass?",
    expectedKnowledge: "No, private methods cannot be overridden because they are not visible to subclasses.",
    candidateAnswer: "Private methods cannot be overridden.",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    minScore: 3,
    maxScore: 3,
  },
  {
    id: "C_02",
    category: "SHORT SEMANTIC / SQL",
    domain: "SQL",
    question: "What keyword removes duplicate rows from an SQL SELECT query?",
    expectedKnowledge: "DISTINCT",
    candidateAnswer: "DISTINCT",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "D_01",
    category: "LONG CORRECT / PYTHON",
    domain: "Python",
    question: "Explain the difference between mutable and immutable data types in Python with examples.",
    expectedKnowledge: "Mutable objects like lists and dictionaries can be modified in place, while immutable objects like tuples and strings cannot be changed after creation.",
    candidateAnswer: "Mutable objects such as lists and dictionaries can be modified after creation without changing their memory address. In contrast, immutable objects like strings, integers, and tuples cannot be altered in place; modifying them creates a new object in memory.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "CORRECT",
    minScore: 4,
    maxScore: 5,
  },
  {
    id: "E_01",
    category: "PARTIAL CONCEPT / ACID",
    domain: "DBMS",
    question: "Explain the four ACID properties in database management systems.",
    expectedKnowledge: "Atomicity ensures all-or-nothing transactions, Consistency preserves valid state invariants, Isolation prevents concurrent interference, and Durability guarantees committed changes persist.",
    candidateAnswer: "Atomicity means the transaction executes all or nothing, and Consistency ensures data remains valid.",
    maxMarks: 5,
    difficulty: "hard",
    round: "technical",
    expectedStatus: "PARTIALLY_CORRECT",
    minScore: 2,
    maxScore: 3,
  },
  {
    id: "F_01",
    category: "WRONG CONCEPT / SECURITY",
    domain: "Security",
    question: "What is Cross-Site Scripting (XSS)?",
    expectedKnowledge: "XSS is a vulnerability where malicious scripts are injected into trusted websites and executed in the victim's browser.",
    candidateAnswer: "XSS is an attack where malicious SQL queries are sent to manipulate database tables and extract passwords.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "INCORRECT",
    expectedScore: 0,
  },
  {
    id: "I_01",
    category: "SQL AGGREGATION",
    domain: "SQL",
    question: "Write an SQL query to calculate the maximum salary from the Employees table.",
    expectedKnowledge: "SELECT MAX(salary) FROM Employees;",
    candidateAnswer: "SELECT MAX(salary) FROM Employees;",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "J_01",
    category: "JAVA INTERFACE",
    domain: "Java",
    question: "What are the default modifiers for variables declared inside a Java interface?",
    expectedKnowledge: "public static final",
    candidateAnswer: "public static final",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    expectedScore: 3,
  },
  {
    id: "K_01",
    category: "PYTHON GIL",
    domain: "Python",
    question: "What is the Global Interpreter Lock (GIL) in Python?",
    expectedKnowledge: "The GIL is a mutex that allows only one native thread to execute Python bytecode at a time.",
    candidateAnswer: "The Global Interpreter Lock is a mechanism in CPython that ensures only one thread executes Python bytecode at any single time, preventing multithreaded CPU-bound execution.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "CORRECT",
    minScore: 4,
    maxScore: 5,
  },
  {
    id: "O_01",
    category: "NETWORKING DNS",
    domain: "Networking",
    question: "What is the purpose of the Domain Name System (DNS)?",
    expectedKnowledge: "DNS maps human-friendly domain names to machine-readable IP addresses.",
    candidateAnswer: "DNS translates human-readable domain names into IP addresses so browsers can load internet resources.",
    maxMarks: 3,
    difficulty: "easy",
    round: "technical",
    expectedStatus: "CORRECT",
    minScore: 3,
    maxScore: 3,
  },
  {
    id: "P_01",
    category: "SECURITY HTTPS",
    domain: "Security",
    question: "Why is HTTPS preferred over HTTP for sensitive transactions?",
    expectedKnowledge: "HTTPS encrypts data in transit using TLS/SSL to prevent eavesdropping and man-in-the-middle attacks.",
    candidateAnswer: "HTTPS provides end-to-end encryption using SSL/TLS protocols to secure data transmission against eavesdropping and tampering.",
    maxMarks: 5,
    difficulty: "medium",
    round: "technical",
    expectedStatus: "CORRECT",
    minScore: 4,
    maxScore: 5,
  },
  {
    id: "R_01",
    category: "DEBUGGING / NODE",
    domain: "Debugging",
    question: "How do you detect and fix a memory leak in a Node.js application?",
    expectedKnowledge: "Take heap snapshots using Chrome DevTools or heapdump, compare memory allocations, and remove unclosed event listeners or global references.",
    candidateAnswer: "Take heap snapshots using Chrome DevTools or heap profiling, compare retained objects over time, and remove lingering event listeners or global cache references.",
    maxMarks: 5,
    difficulty: "hard",
    round: "technical",
    expectedStatus: "CORRECT",
    minScore: 4,
    maxScore: 5,
  },
  {
    id: "HR_05",
    category: "HR VAGUE RESPONSE",
    domain: "HR",
    question: "Why do you want to join our organization?",
    expectedKnowledge: "Articulate specific interest in company projects, engineering culture, and personal growth contribution.",
    candidateAnswer: "Because your company is good and big.",
    maxMarks: 20,
    difficulty: "easy",
    round: "hr",
    expectedStatus: "INCORRECT",
    maxScore: 0,
  },
  {
    id: "PROJ_03",
    category: "PROJECT SCALABILITY",
    domain: "Project",
    question: "How did you scale your database for high read concurrency?",
    expectedKnowledge: "Implemented database read replicas with connection pooling and an in-memory Redis cache layer.",
    candidateAnswer: "We set up database read replicas to distribute query traffic, added connection pooling, and integrated Redis cache to serve frequent reads.",
    maxMarks: 10,
    difficulty: "medium",
    round: "project",
    expectedStatus: "CORRECT",
    minScore: 9,
    maxScore: 10,
  },
];

let passed = 0;
let failed = 0;

console.log("================================================================================");
console.log("EXECUTION TABLE:");
console.log("================================================================================\n");

for (let i = 0; i < TEST_CASES.length; i++) {
  const tc = TEST_CASES[i];
  const res = judgeAnswer({
    question: tc.question,
    expectedKnowledge: tc.expectedKnowledge,
    candidateAnswer: tc.candidateAnswer,
    maxMarks: tc.maxMarks,
    round: tc.round,
    difficulty: tc.difficulty,
    questionId: tc.id,
  });

  const score = res.score;
  const status = res.status;

  let pass = true;
  let failReason = "";

  if (tc.expectedScore !== undefined && score !== tc.expectedScore) {
    pass = false;
    failReason = `Score mismatch: expected ${tc.expectedScore}, got ${score}`;
  } else if (tc.minScore !== undefined && score < tc.minScore) {
    pass = false;
    failReason = `Score too low: expected >= ${tc.minScore}, got ${score}`;
  } else if (tc.maxScore !== undefined && score > tc.maxScore) {
    pass = false;
    failReason = `Score too high: expected <= ${tc.maxScore}, got ${score}`;
  }

  if (status !== tc.expectedStatus) {
    pass = false;
    failReason += ` | Status mismatch: expected ${tc.expectedStatus}, got ${status}`;
  }

  if (pass) {
    passed++;
    console.log(`[PASS] ${tc.id.padEnd(8)} [${tc.category.padEnd(20)}] (${tc.domain.padEnd(12)}) Score: ${String(score).padStart(2)}/${tc.maxMarks} | Status: ${status.padEnd(17)} | Source: ${res.evaluationSource}`);
  } else {
    failed++;
    console.error(`[FAIL] ${tc.id.padEnd(8)} [${tc.category.padEnd(20)}] (${tc.domain.padEnd(12)}) Score: ${String(score).padStart(2)}/${tc.maxMarks} | Status: ${status.padEnd(17)} | REASON: ${failReason}`);
  }
}

console.log("\n================================================================================");
console.log(`TEST SUITE RESULT: ${passed}/${TEST_CASES.length} PASSED (${failed} failed)`);
console.log("================================================================================");

if (failed > 0) {
  process.exit(1);
}
