

/**
 * Application Route Paths Constants
 * Preserves exact URL mapping across all 54 frontend routes.
 */
export const ROUTES = {
  HOME: "/",
  SIGNUP: "/signup",
  REGISTRATION_SUCCESS: "/registration-success",
  TERMS: "/terms-and-conditions",
  PRIVACY: "/privacy-policy",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  ABOUT: "/about",
  CONTACT: "/contact",
  ACHIEVEMENTS: "/achievements",
  BOOKMARKS: "/bookmarks",
  REAL_INTERVIEW: "/interview",
  REAL_INTERVIEW_SESSION: "/interview/:sessionId",
  REAL_INTERVIEW_RESULT: "/real-interview/result/:sessionId",
  RESULTS: "/results",
  INTERVIEW_HISTORY: "/interview-history",
  INTERVIEW_PRACTICE: "/interview-practice",
  COMPANY_MOCK: "/company-mock",
  COMPANY_MOCK_RESULT: "/company-mock/result/:attemptId",
  COMPANY_MOCK_HISTORY: "/company-mock-history",
  COMPANY_ANALYTICS: "/company-analytics",
  AVAILABLE_TESTS: "/available-tests",
  TEST_ENGINE: "/test-engine/:id",
  TEST_RESULT: "/test-result/:attemptId",
  APTITUDE: "/aptitude",
  APTITUDE_ASSESSMENT: "/aptitude-assessment/:difficulty",
  APTITUDE_ROUND: "/aptitude-round/:topic",
  APTITUDE_HISTORY: "/aptitude-history",
  CODING_ASSESSMENT: "/coding-assessment/:assessmentId",
  CODING_ASSESSMENT_LIST: "/coding-assessment",
  CODING_ASSESSMENT_HISTORY: "/coding-assessment/history",
  CODING_ROUND: "/coding-round/test",
  CODING_HISTORY: "/coding-history",
  PLACEMENT_DASHBOARD: "/placement-dashboard",
  LEADERBOARD: "/leaderboard",
  MOCK_OA: "/mock-oa",
  PERFORMANCE_GRAPHS: "/performance-graphs",
  QUESTION_ANALYTICS: "/question-analytics",
  INDIVIDUAL_TECHNICAL_PRACTICE: "/individual-practice/technical/:sessionId",
  INDIVIDUAL_TECHNICAL_RESULT: "/individual-practice/technical/result/:sessionId",
  INDIVIDUAL_PROJECT_PRACTICE: "/student/individual-project/practice/:sessionId",
  INDIVIDUAL_PROJECT_RESULT: "/student/individual-project/result/:sessionId",
  ADMIN_DASHBOARD: "/admin/dashboard",
  SYSTEM_ADMIN_DASHBOARD: "/admin/system-admin",
  TEACHER_MANAGEMENT: "/admin/teachers",
  PREMIUM_MANAGEMENT: "/admin/premium",
  STUDENTS_LIST: "/admin/students",
  STUDENT_DETAILS: "/admin/students/:id",
  CREATE_TEST: "/admin/create-test",
  ASSIGNED_TESTS: "/admin/assigned-tests",
  COMPANY_MANAGEMENT: "/admin/companies",
  CODING_QUESTION_MANAGEMENT: "/admin/coding-questions",
  APTITUDE_MANAGEMENT: "/admin/aptitude",
  AUDIT_LOGS: "/admin/audit-logs",
  SYSTEM_CONFIG: "/admin/system-config",
  ADMIN_PLACEMENT_ANALYTICS: "/admin/placement-analytics",
  ADMIN_TECHNICAL_MANAGEMENT: "/admin/technical-management",
  ANALYTICS_DASHBOARD: "/admin/analytics",
  MOCK_QUESTION_MANAGEMENT: "/admin/mock-questions",
  ADMIN_CODING_ASSESSMENTS: "/admin/coding/assessments",
  ADMIN_CODING_RESULTS: "/admin/coding/results/:id",
};
